github:
  description: "Apache Sling Models bnd Plugin"
  homepage: "https://sling.apache.org/"
  labels:
  - "sling"
  - "sling-models"
  - "bnd"
  - "sling-bnd-plugins"
  autolink_jira:
  - "SLING"
  - "OAK"
  - "JCR"
  - "JCRVLT"
  - "INFRA"
  - "FELIX"
  - "MNG"
notifications:
  jira_options: "link"
