github:
  description: "Apache Sling Models bnd Plugin"
  homepage: "https://sling.apache.org/"
  labels:
  - "sling"
  - "sling-models"
  - "bnd"
  - "sling-bnd-plugins"
  autolink_jira:
  - "SLING"
  - "OAK"
  - "JCR"
  - "JCRVLT"
  - "INFRA"
  - "FELIX"
  - "MNG"
  pull_requests:
    del_branch_on_merge: true
  protected_branches:
    master: {}
notifications:
  jira_options: "link"
  pullrequests_bot_sonarcloud: "commits@sling.apache.org"
